version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: motorsport-api
    restart: always
    ports:
      - "${API_PORT}:${API_INTERNAL_PORT}"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./user_data/photos:/app/wwwroot/uploads
    environment:
      # ENV
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      # DB 
      - ConnectionStrings__DefaultConnection=Server=${DB_HOST};Database=${DB_NAME};User=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=True
      # JWT
      - JwtSettings__Secret=${JWT_SECRET}
      - JwtSettings__Issuer=${JWT_ISSUER}
      - JwtSettings__Audience=${JWT_AUDIENCE}
      - JwtSettings__ExpirationHours=${JWT_EXPIRATION_HOURS}

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: motorsport-db
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:1433"
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/localhost/1433' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data: